"""Ubah structure table User

Revision ID: 19d835a3a3e7
Revises: 23a86bf1db5a
Create Date: 2022-09-19 10:57:43.461571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19d835a3a3e7'
down_revision = '23a86bf1db5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nama', sa.String(length=250), nullable=False))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('user', 'nama')
    # ### end Alembic commands ###
