"""hapus unik table User

Revision ID: 9b8b28498c1d
Revises: 19d835a3a3e7
Create Date: 2022-09-19 10:59:03.477096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b8b28498c1d'
down_revision = '19d835a3a3e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
