"""membuat table user

Revision ID: f8bbf9d0a578
Revises: 
Create Date: 2022-09-16 13:56:59.995491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8bbf9d0a578'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_table('tb_siswa')
    op.drop_table('tb_user')
    op.drop_table('siswa_node')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('siswa_node',
    sa.Column('id_siswa', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nisn', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('nama_siswa', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('alamat', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_siswa'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_user',
    sa.Column('id_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nama_user', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_siswa',
    sa.Column('nis', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('nama', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('umur', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('alamat', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('nis'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
